---
- name: Include debian
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install alacritty
  become: true
  package:
    name:
      - alacritty
    state: present

- name: Create ~/.config/alacritty directory
  become: false
  file:
    path: ~/.config/alacritty/alacritty.yml
    state: directory

- name: Generate alacritty config files
  become: false
  template:
    src: alacritty.yml.j2
    dest: ~/.config/alacritty/alacritty.yml
