---
- name: Include steamos
  ansible.builtin.include_tasks: steamos.yml
  when: ansible_distribution == 'SteamOS'

- name: Include debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian' and ansible_distribution != 'SteamOS'

- name: Include archlinux
  ansible.builtin.include_tasks: archlinux.yml
  when: ansible_os_family == 'Archlinux' and ansible_distribution != 'SteamOS'

- name: Include darwin
  ansible.builtin.include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install alacritty
  become: true
  ansible.builtin.package:
    name:
      - alacritty
    state: present
  when: ansible_os_family not in ['Archlinux', 'Darwin'] and ansible_distribution != 'SteamOS'

- name: Create ~/.config/alacritty directory
  become: false
  ansible.builtin.file:
    path: ~/.config/alacritty
    state: directory
    mode: '0755'

- name: Generate alacritty config files
  become: false
  ansible.builtin.template:
    src: alacritty.toml.j2
    dest: ~/.config/alacritty/alacritty.toml
    mode: '0644'
