---
- name: Uninstall alacritty
  become: true
  package:
    name:
      - alacritty
    state: absent

- name: Destroy ~/.config/alacritty directory
  become: false
  file:
    path: ~/.config/alacritty
    state: absent
